import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WsProvider } from "@/lib/ws";
import { GameSessionProvider } from "@/lib/gameSession";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <WsProvider>
          <GameSessionProvider>{children}</GameSessionProvider>
        </WsProvider>
      </body>
    </html>
  );
}
